API_METHODS = [
    "B2Binpay (-)",
    "B2BInPay GPS (-)",
    "ZotaPay Bank IDR GPS (-)",
    "Bitpay (-)",
    "Dusupay (-)",
    "GrowPay Netbanking India (-)",
    "Growpay UPI India (-)",
    "GrowPay Egypt (-)",
    "HelloVietnam (-)",
    "Jpay P2P China (-)",
    "KoraPay Wire (-)",
    "MyPay P2P China (-)",
    "Neteller (-)",
    "Paytrust88 (-)",
    "Paytoday (-)",
    "Perfectmoney (-)",
    "P2P Zotapay (-)",
    "P2P Korea Z (-)",
    "Praxis P2P (-)",
    "Safaricom M-Pesa Kenya (-)",
    "Skrill (-)",
    "Ozow EFT GPS (-)",
    "TC Pay Wallet (-)",
    "UsePay P2P (-)",
    "Zotapay/Nganluong/Vietnam (-)",
    "Zotapay Banking Vietnam (-)",
    "Payretailers PIX Brazil (-)",
    "Payretailers SPEI Mexico (-)",
]

EMAIL_TEMPLATE = {
    "Zotapay Banking Vietnam (-)": "Online banking confirmation - withdrawal is pending",
    "KoraPay Wire (-)": "Request for bank statement - withdrawal pending",
    "P2P Zotapay (-)": "CUP: Request for bank statement – withdrawal is pending",
    "Growpay UPI India (-)": "Request for GrowPay screenshot, deposit processed",
    "GrowPay Netbanking India": "Request for Online Banking India account number confirmation -  deposit processed",
    "Jpay P2P China (-)": "CUP: Request for bank statement – withdrawal is pending",
    "MyPay P2P China (-)": "CUP: Request for bank statement – withdrawal is pending",
    "Paytrust88 (-)": "Request for screenshot, deposit processed",
    "Paytoday (-)": "Request for bank statement - withdrawal is pending",
}
