RESTRICTED_COUNTRIES = [
    "AUSTRIA",
    "FRANCE",
    "MALTA",
    "BELGIUM",
    "GERMANY",
    "NETHERLANDS",
    "BULGARIA",
    "GREECE",
    "POLAND",
    "CROATIA",
    "HUNGARY",
    "PORTUGAL",
    "CYPRUS",
    "IRELAND",
    "ROMANIA",
    "CZECH REPUBLIC",
    "ITALY",
    "SLOVAKIA",
    "DENMARK",
    "LATVIA",
    "SLOVENIA",
    "ESTONIA",
    "LITHUANIA",
    "SPAIN",
    "FINLAND",
    "LUXEMBOURG",
    "SWEDEN",
    "UNITED KINGDOM",
    "UNITED STATES",
    "MAURITIUS",
    "JAPAN",
    "CANADA",
    "HAITI",
    "IRAN",
    "SURINAME",
    "THE DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA",
    "PUERTO RICO",
    "BRAZIL",
    "QUEBEC",
    "IRAQ",
    "SYRIA",
    "CUBA",
]
